export const OWNER_CONSTANTS = {
  ONBOARDING_STEPS: [
    'PERSONAL_DETAILS',
    'KYC_VERIFICATION',
    'BUSINESS_DETAILS',
    'BANK_DETAILS',
    'PROPERTY_REGISTRATION',
    'LOCATION_MAP',
    'BUILDING_LAYOUT',
    'ROOM_BED_GENERATION',
    'SUBSCRIPTION_SELECT',
    'SUBMIT_APPROVAL'
  ],
};
