export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    SEND_OTP: "/auth/send-otp",
    VERIFY_OTP: "/auth/verify-otp",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    ME: "/auth/me",
  },
  PROPERTIES: {
    PUBLIC: "/properties",
    BY_ID: (id: string) => `/properties/${id}`,
    CREATE: "/properties",
    SUMMARY: "/properties/owner-summary",
  },
  RESIDENTS: {
    ONBOARD: "/residents/onboard",
    DIRECTORY: "/residents/directory",
    PORTAL_ME: "/residents/portal/me",
    STATUS: (id: string) => `/residents/${id}/status`,
    STATUS_HISTORY: (id: string) => `/residents/${id}/status-history`,
    VISITOR_PASS: "/residents/visitor-pass",
    GATE_PASS: "/residents/gate-pass",
    MEAL_SKIP: "/residents/meal-skip",
  },
  BEDS: {
    STATUS: (id: string) => `/beds/${id}/status`,
    HOLDS: "/beds/holds",
    HOLD_RELEASE: (id: string) => `/beds/holds/${id}`,
  },
  ROOMS: {
    CONVERT: (id: string) => `/rooms/${id}/convert`,
    TRANSFERS_REQUEST: "/rooms/transfer-requests",
    TRANSFERS: "/rooms/transfer-requests",
    TRANSFER_APPROVE: (id: string) => `/rooms/transfer-requests/${id}/approve`,
    TRANSFER_REJECT: (id: string) => `/rooms/transfer-requests/${id}/reject`,
    TRANSFER_COMPLETE: (id: string) => `/rooms/transfer-requests/${id}/complete`,
  },
  BILLING: {
    CREATE_ORDER: "/payments/create-order",
    VERIFY_PAYMENT: "/payments/verify",
    INVOICE_DOWNLOAD: (id: string) => `/billing/invoices/${id}/pdf`,
  },
  COMPLAINTS: {
    BASE: "/complaints",
    STATUS: (id: string) => `/complaints/${id}/status`,
  },
  RESIDENT_MANAGEMENT: {
    STATUS: (id: string) => `/residents/${id}/status`,
    STATUS_HISTORY: (id: string) => `/residents/${id}/status-history`,
    BED_STATUS: (id: string) => `/beds/${id}/status`,
    BED_HOLD: "/beds/holds",
    BED_HOLD_RELEASE: (id: string) => `/beds/holds/${id}`,
    BED_HOLDS: "/beds/holds",
    TRANSFERS_REQUEST: "/rooms/transfer-requests",
    TRANSFERS: "/rooms/transfer-requests",
    TRANSFER_APPROVE: (id: string) => `/rooms/transfer-requests/${id}/approve`,
    TRANSFER_REJECT: (id: string) => `/rooms/transfer-requests/${id}/reject`,
    TRANSFER_COMPLETE: (id: string) => `/rooms/transfer-requests/${id}/complete`,
  },
} as const;
